dist: trusty
language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./_scripts/cibuild
script:
- "./_scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: Y88wPxgG/YCJMnL5ZT6nvabrZN6fJLKoHwkklBaaePfqycKzVaWH3JPiZePPp0fx5gztXmYd/ihn3QFyHTgYU8T2uW3TPeSPCCx2hLzcNseftFkndomqFvVlp9NmjM5H3urRV5tNDE/Ek48Sx3PAHt5paRW7iAa8dfliF9qMbS0MENjwFCEJWMIcjQQdIheFhNFVz6e73bogSttSE6fMkiF29TRZVNln2cPKBc6pEOpINPp/b4YOIaLUqmgT6HaezM5WiAdSj/fnJeLaAkHFBlW2CpYZdPf2Lu8LrUbIReI7MAr5aDNG2fhuCpQ/m35PJ2+uWYLYTpeHZcgOtm3EPJZTioWuIHLvrXosGu90aDjViQjTNlQtEdKrY+4qYcSe42AhizIH94c7OcRBxpHHGzVhh0QD/CarWf31AX+UNfzFAu1VlbelwsfEDgOkpH61pkeJcOeKiM3BXTNb2jbmIuSqs4smViOkr5/G6cSMY1lNvC9lrmXfN0H9GQlBlrkZHA0hV+eMv/z711X/+UW16M2Ktksp92rqH7krFgO/suVF096twVAIaOF4a05liWoePLiiVcgWZdmox5LyxA/OjizmmL4t2MTbd1WhRagwffNg3KdENuGQw/llAHnPg45nbhjWvj2aYfeUBAfBy71ddHBm5uubjeGeDXJnZ+ooe9A=
  - secure: LMvB5XZycRQfEnmSEvXomhA+q1o8kQ0j+8gkn3EkhLYCsPNOQse+G8WJHfRLdbPxlo+j7xoNwPOqWVF4IzBM6iqyD14D77WBOQwf+YgLQYa7o5wAQ6ES3ehXAkTYb8ooH91WxIeQmDakwCx9yGjox4F1+L2aH0OMQA6E50bMVeN3AEJDr+OptKqUAZk0W26a3IPixMPX2YWFSodqtRgIpuZWlqiMjh7E9WgXL7Vdha0PTTZh9lKNbL8iKJdyd2vdWJKfmsKfdh3O1LvAFPHaM741omSeFhsyePbHah03H89fJlCbi0jZkch9oZcl47hR62J+oN9PoMCLhaqP/4sZRbKmLmJsuKIRdK/3XFFsKReNmkJUTZB2w+fYHGCvFjE39DNxW5JnPtoqcCBlUl88Q9EKrOEka0LCzvBLDZREo30CBM1UKi/trXapcv10yZg0BwqLMA1KDoYb+SpXv2dWODa14O6kYuzuWDbgp/Cm39vC0zhWcFZ5e+VYw75dVZrbtywD7kBN8zhZBebHe3v/Wtuql4FydFSeVLXS+Q3KST+8mlOTPAn44bnj288Y0ic0xNZggoTLDeliWug5sFlvP7fr04UrDX5OysdHW9M1A62kB33znzOlK+VdLwr2Zvjc6RRxUC/YEUlE2OGEPtI4ATfPBJA+Nv9sssvMlyG4CSg=
addons:
  ssh_known_hosts: 
  - suss.caves.org.au
  - 45.56.82.247
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script:
  - ping -c 6 45.56.82.247
  - ssh suss@suss.caves.org.au ls
  - rsync -r --delete-after -vv --rsync-path=/usr/bin/rsync $TRAVIS_BUILD_DIR/_site/ ${user}@${domain}:/home/suss/public_html/
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_56521efdd71b_key -iv $encrypted_56521efdd71b_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
